### ISSUE TITLE
unclassing a factor

### ISSUE THREAD

**Issue by jdblischak** [karthik/bc#26]
In R-basics/02-data-structures.Rmd:

```
`unclass(x)` strips out the class information.
```

IMO this is too advanced for an introduction to R data structures. Could you provide an example so that the students could understand how it would be useful to them? I'd suggest replacing this with a demonstration of how to convert from a factor to a character string since that is a much more common operation:

   `as.character(x)` converts a factor to a character vector.

**Comment by karthik** [comment]
OK, sure. It was just meant to show them additional possibilities since we do discuss classes. Happy to make suggested changes.
