### ISSUE TITLE
regex in data-manipulation exercise

### ISSUE THREAD

**Issue by jdblischak** [karthik/bc#35]
```
* Reads all file names in your working directory with a `.csv` extension.
```

I think this is too advanced. Requiring the students to look up how to write a regular expression in R (or convert a glob with `glob2rx`) will delay them from practicing the data manipulation skills that they just learned.

**Comment by karthik** [comment]
Good point. I added it as an optional advanced exercise to keep the faster students engaged if they finished early. This part doesn't require any complex regex and we could introduce the idea before covering more if it in the shell section. 

Remove it or explicitly add that it's an advanced exercise and should only be attempted if people finish the rest?

**Comment by jdblischak** [comment]
How about offering two versions? The harder version would be the original problem reading in all .csv files in the directory. The easier version would be to just explicitly create a list of length two containing "species1.csv" and "species2.csv". Then the problem would continue from there using `read.csv` with `lapply` to read in the data.
