### ISSUE TITLE
Describe package structure

### ISSUE THREAD

**Issue by jdblischak** [karthik/bc#39]
Both the testing and documentation lectures mention R package structures. It would be useful to provide a basic description of R packages and their directory structure. 

In testing.Rmd:

> Save all tests in a folder. In the case of a package, the folder is located under 
> `inst/tests`. Otherwise save into a file that has the word `test` in the title. example. `test_script.R`

In documentation.md:

> After this markup has been processed by `roxygen2` you get a file with the same name and extension `.Rd` (R documentation) in the `man/` folder.

**Comment by karthik** [comment]
We can summarize from [this section](http://cran.r-project.org/doc/manuals/R-exts.html#Package-structure) of writing R packages. However, I don't see an organic place for this to go unless we start a new file on Writing R packages. It doesn't make sense in documentation.md or testing.md

thoughts?

**Comment by jdblischak** [comment]
I think it would make the most sense to be at the beginning of documentation.md because you mention package structure right after the motivation for documenting code. I propose a structure like the following:
- Motivation for documenting code
- R package structure
- The role of roxygen2 in facilitating code documentation when writing R packages.

But that does bring up a bigger question: does it make sense to document functions in the style of roxygen2 outside of package development? I know of no way to generate the nice documentation pages for standalone scripts. While certainly it doesn't hurt to have the documentation in roxgygen2 format, that certainly raises the activation energy required to document functions without any of the extra payoff.
